spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 30000
      connection-timeout: 20000
      maximum-pool-size: 3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    enabled: true
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8